services:
  - type: web
    name: resume-scanner-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: DB_NAME
        value: resume_scanner
      - key: ADDITIONAL_CORS_ORIGINS
        sync: false
    disks:
      - name: uploads
        mountPath: /opt/render/project/src/backend/uploads
        sizeGB: 1 